[package]
name = "aoc-2020-day6"
version = "0.1.0"
authors = ["Bouillaguet Quentin <git@desplandis.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom="6"
